In [3]:
# Data Dividation
# workflow of ML
# Data Ingestion ---> Data Cleaning and Preprocessing ---> Based on the target column
# we have to select ml model ---> Model training --> Model prediction --> Model performance Evaluation

In [4]:
# df ---> x(input), y(target)
# x ---> x_train, x_test
# y ---> y_train, y_test
# Model training(x_train, y_train)
# y_pred = Model Predictio(x_test)
# Model Performance (y_test, y_pred)

In [5]:
# 1+1=2
# 1+2=3
# 1+3=4
# 1+4=5
# x = [1+1,1+2,1+3,1+4]
# y = [2,3,4,5]
# x_train = [1+1,1+2,1+3]
# y_train = [2,3,4]
# x_test = [1+4]
# y_test = [5]

In [6]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv('/content/placement.csv')

In [9]:
df.head(2)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [10]:
df.shape

(100, 3)

In [11]:
x = df.drop(columns=['placed'])

In [12]:
y = df['placed']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
print("Total Shape Of df:", df.shape)
print('----*******************----')
print("Total Input Data Shape:", x.shape)
print("x_train Data Shape:", x_train.shape)
print("x_test Data Shape:", x_test.shape)
print('----*******************----')
print("Total Output Data Shape:", y.shape)
print("y_train Data Shape:", y_train.shape)
print("y_test Data Shape:", y_test.shape)

Total Shape Of df: (100, 3)
----*******************----
Total Input Data Shape: (100, 2)
x_train Data Shape: (80, 2)
x_test Data Shape: (20, 2)
----*******************----
Total Output Data Shape: (100,)
y_train Data Shape: (80,)
y_test Data Shape: (20,)

In [17]:
# df(100,3) = x(100,2) + y(100,1)
# x(100,2) = x_train(80,2) + x_test(20,2)
# y(100,1) = y_train(80,1) + y_test(20,1)

In [18]:
# Task Covid dataset convert into categorical to numerical,
# missing data handle
# df --> x,y,x_train, x_test, y_train, y_test

In [20]:
covid_df = pd.read_csv('/content/covid_toy.csv')

In [21]:
covid_df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [22]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [23]:
covid_df.isna().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [25]:
covid_df['fever'] = covid_df['fever'].fillna(covid_df['fever'].mean())

In [26]:
covid_df.isna().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [28]:
covid_df['gender'] = covid_df['gender'].map({'Female':1 , 'Male':0})

In [29]:
covid_df['cough'] = covid_df['cough'].map({'Mild':0, 'Strong' : 1})

In [30]:
covid_df['has_covid'] = covid_df['has_covid'].map({'Yes':1, 'No':0})

In [32]:
covid_df.dtypes

age            int64
gender         int64
fever        float64
cough          int64
city          object
has_covid      int64
dtype: object

In [33]:
covid_df = covid_df.drop(columns=['city'])

In [43]:
covid_x = covid_df.drop(columns=['has_covid'])
print(covid_x)

    age  gender  fever  cough
0    60       0  103.0      0
1    27       0  100.0      0
2    42       0  101.0      0
3    31       1   98.0      0
4    65       1  101.0      0
..  ...     ...    ...    ...
95   12       1  104.0      0
96   51       1  101.0      1
97   20       1  101.0      0
98    5       1   98.0      1
99   10       1   98.0      1

[100 rows x 4 columns]

In [44]:
covid_y = covid_df['has_covid']
print(covid_y)

0     0
1     1
2     0
3     0
4     0
     ..
95    0
96    1
97    0
98    0
99    1
Name: has_covid, Length: 100, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
covid_x_train, covid_x_test, covid_y_train, covid_y_test = train_test_split(covid_x,covid_y,test_size=0.2,random_state=42)

In [47]:
print("Total Shape Of covid_df:", covid_df.shape)
print('----*******************----')
print("Total Input Data Shape:", covid_x.shape)
print("x_train Data Shape:", covid_x_train.shape)
print("x_test Data Shape:", covid_x_test.shape)
print('----*******************----')
print("Total Output Data Shape:", covid_y.shape)
print("y_train Data Shape:", covid_y_train.shape)
print("y_test Data Shape:", covid_y_test.shape)

Total Shape Of covid_df: (100, 5)
----*******************----
Total Input Data Shape: (100, 4)
x_train Data Shape: (80, 4)
x_test Data Shape: (20, 4)
----*******************----
Total Output Data Shape: (100,)
y_train Data Shape: (80,)
y_test Data Shape: (20,)

In [48]:
print(covid_x_train)

    age  gender  fever  cough
55   81       1  101.0      0
88    5       1  100.0      0
26   19       1  100.0      0
42   27       0  100.0      0
69   73       1  103.0      0
..  ...     ...    ...    ...
60   24       1  102.0      1
71   75       1  104.0      1
14   51       0  104.0      0
92   82       1  102.0      1
51   11       1  100.0      1

[80 rows x 4 columns]

In [49]:
print(covid_x_test)

    age  gender       fever  cough
83   17       1  104.000000      0
53   83       0   98.000000      0
70   68       1  101.000000      1
45   72       0   99.000000      0
44   20       0  102.000000      1
39   50       1  103.000000      0
22   71       1   98.000000      1
80   14       1   99.000000      0
10   75       1  100.844444      0
0    60       0  103.000000      0
18   64       1   98.000000      0
30   15       0  101.000000      0
73   34       0   98.000000      1
33   26       1   98.000000      0
90   59       1   99.000000      1
4    65       1  101.000000      0
76   80       0  100.000000      0
77    8       1  101.000000      0
12   25       1   99.000000      1
31   83       0  103.000000      0

In [50]:
print(covid_y_train)

55    1
88    0
26    1
42    1
69    0
     ..
60    1
71    0
14    0
92    0
51    1
Name: has_covid, Length: 80, dtype: int64

In [51]:
print(covid_y_test)

83    0
53    1
70    0
45    0
44    0
39    0
22    1
80    1
10    0
0     0
18    1
30    1
73    1
33    0
90    0
4     0
76    1
77    0
12    0
31    0
Name: has_covid, dtype: int64