In [22]:
# Introduction to pandas ---->
# Pandas is an open-source library which is used for
# handle data manipulation and analysis.

In [23]:
import pandas as pd

In [24]:
# data Structure of pandas ---->
# (1). Series ----> It is one-dimensional array and it returns only values not column name.

# (2). DataFrame ----> It is multi-dimensional array and it returns values with name

In [25]:
# Series

In [26]:
a = pd.Series([1,34,78,90])
a

0     1
1    34
2    78
3    90
dtype: int64

In [27]:
type(a)

pandas.core.series.Series

In [28]:
# DataFrame

In [29]:
a = {
    "Emp_id": [1,2,3,4,5],
    "Name": ['Sam', 'Raj', 'Rohit', 'Karan', 'Abhishek'],
    "Department": ['IT', 'Sales', 'IT', 'IT', 'Sales'],
    "Working_hours": [8,9,8,8,9]
}

In [30]:
a

{'Emp_id': [1, 2, 3, 4, 5],
 'Name': ['Sam', 'Raj', 'Rohit', 'Karan', 'Abhishek'],
 'Department': ['IT', 'Sales', 'IT', 'IT', 'Sales'],
 'Working_hours': [8, 9, 8, 8, 9]}

In [31]:
type(a)

dict

In [32]:
df = pd.DataFrame(a)

In [33]:
df

   Emp_id      Name Department  Working_hours
0       1       Sam         IT              8
1       2       Raj      Sales              9
2       3     Rohit         IT              8
3       4     Karan         IT              8
4       5  Abhishek      Sales              9

In [34]:
#export this df into csv

In [35]:
df.to_csv("emp_data.csv")

In [36]:
df.to_csv("emp_data_new.csv", index=False)

In [37]:
# Import this df using pandas

In [38]:
df_1 = pd.read_csv("emp_data_new.csv")

In [39]:
df_1

   Emp_id      Name Department  Working_hours
0       1       Sam         IT              8
1       2       Raj      Sales              9
2       3     Rohit         IT              8
3       4     Karan         IT              8
4       5  Abhishek      Sales              9

In [40]:
# uk-- top 5 hotels data

In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('/content/covid_toy.csv')

In [43]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [44]:
df.head() # if we want only top data then we will use head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [45]:
df.tail() # it will return last 5 rows

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [46]:
df.shape

(100, 6)

In [47]:
df.sample(3) # it will return random indexed data .

    age  gender  fever   cough       city has_covid
33   26  Female   98.0    Mild    Kolkata        No
78   11    Male  100.0    Mild  Bangalore       Yes
22   71  Female   98.0  Strong    Kolkata       Yes

In [48]:
# if we want to check total columns in a dataframe
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [49]:
df.dtypes # we want to check datatype of columns

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [50]:
# if we want to check overall information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [51]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [52]:
# returns a new dataframe containing only categorical and object columns
categorical_df = df.select_dtypes(include=['category','object'])
categorical_df

    gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
..     ...     ...        ...       ...
95  Female    Mild  Bangalore        No
96  Female  Strong    Kolkata       Yes
97  Female    Mild  Bangalore        No
98  Female  Strong     Mumbai        No
99  Female  Strong    Kolkata       Yes

[100 rows x 4 columns]

In [53]:
#option 1
# return a new dataframe containing only integer colums
int_df = df.select_dtypes(include=['category','int'])
int_df

    age
0    60
1    27
2    42
3    31
4    65
..  ...
95   12
96   51
97   20
98    5
99   10

[100 rows x 1 columns]

In [54]:
#option 2
df_int = df.select_dtypes(include='int')
df_int.columns.to_list()

['age']

In [55]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [56]:
#if we want check missing data in a df then we will use
# df.isnull().sum()

In [57]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [58]:
df['fever'].mean()

np.float64(100.84444444444445)

In [59]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [60]:
#if i want to check total sub-categories in a column then we will use df.value.count()

In [61]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [62]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [63]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64