In [82]:
import numpy as np
import pandas as pd

In [83]:
df = pd.read_csv('placement.csv')

In [84]:
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [85]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [86]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [87]:
df.describe()

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [89]:
top_left_corner_df = df.iloc[:4, :3] #iloc[row_range, column_range]
top_left_corner_df

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [90]:
df.loc[1:3, ['cgpa', 'placed']] # loc[row_range, column_name]

   cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [91]:
s = df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [92]:
p = df.dtypes
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [93]:
df['cgpa'].dtypes

dtype('float64')

In [94]:
b = df.empty #it returns true if there any missing data in dataframe otherwise return false
b

False

In [95]:
df.isnull().sum() # for check missing values

cgpa            0
resume_score    0
placed          0
dtype: int64

In [96]:
df = df.dropna() # for remove missing row

In [97]:
i = df.ndim # number of axes (it is 2)
i

2

In [98]:
t = df.shape # shape = n(rows), n(columns)
t
df.shape[0] #total rows in data
df.shape[1] # total columns in data

3

In [99]:
df.size # row count * column count

300

In [100]:
a = df.values #get a number
a

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [101]:
# copy()

In [102]:
p = df.sort_values(by = 'resume_score')
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [103]:
top_5_minimum = p.head()
top_5_minimum

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0

In [104]:
top_5_high = p.tail()
top_5_high

    cgpa  resume_score  placed
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

# Churn_Modelling

In [105]:
import pandas as pd

In [106]:
df = pd.read_csv('Churn_Modelling.csv')

In [107]:
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [108]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [110]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [111]:
left = df.iloc[:5, :7]
left

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43

In [112]:
df.loc[4:8, ['Surname', 'Geography']]

    Surname Geography
4  Mitchell     Spain
5       Chu     Spain
6  Bartlett    France
7    Obinna   Germany
8        He    France

In [113]:
s = df.axes

In [114]:
s

[RangeIndex(start=0, stop=10000, step=1),
 Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
        'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
        'IsActiveMember', 'EstimatedSalary', 'Exited'],
       dtype='object')]

In [115]:
coldtype = df.dtypes
coldtype

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [116]:
df.dtypes['Age']

dtype('int64')

In [117]:
df.empty

False

In [118]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [119]:
df = df.dropna()

In [120]:
df.ndim

2

In [121]:
df.shape

(10000, 14)

In [122]:
df.size

140000

In [123]:
df.values

array([[1, 15634602, 'Hargrave', ..., 1, 101348.88, 1],
       [2, 15647311, 'Hill', ..., 1, 112542.58, 0],
       [3, 15619304, 'Onio', ..., 0, 113931.57, 1],
       ...,
       [9998, 15584532, 'Liu', ..., 1, 42085.58, 1],
       [9999, 15682355, 'Sabbatini', ..., 0, 92888.52, 1],
       [10000, 15628319, 'Walker', ..., 0, 38190.78, 0]], dtype=object)

In [124]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [125]:
p = df.sort_values(by = 'EstimatedSalary')
p

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2362,2363,15791053,Lucciano,709,Germany,Male,45,4,122917.71,1,1,1,11.58,1
9647,9648,15679693,Walker,625,France,Male,31,5,0.00,2,0,1,90.07,0
9010,9011,15786463,Hsing,645,Germany,Female,59,8,121669.93,2,0,0,91.75,1
5548,5549,15639662,Phillips,710,France,Male,38,2,0.00,2,1,0,96.27,0
4989,4990,15602851,Ozioma,629,France,Male,40,9,0.00,1,1,0,106.67,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8926,8927,15709136,Adams,620,France,Male,28,8,0.00,2,1,1,199909.32,0
9096,9097,15762331,Moss,569,France,Male,37,9,178755.84,1,1,0,199929.17,0
4417,4418,15697270,Gannon,608,Spain,Male,27,4,153325.10,1,1,1,199953.33,0
3580,3581,15634359,Dyer,639,Germany,Female,41,5,98635.77,1,1,0,199970.74,0
6646,6647,15662021,Lucciano,685,Spain,Female,42,2,0.00,2,0,0,199992.48,0

In [126]:
p.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2362,2363,15791053,Lucciano,709,Germany,Male,45,4,122917.71,1,1,1,11.58,1
9647,9648,15679693,Walker,625,France,Male,31,5,0.00,2,0,1,90.07,0
9010,9011,15786463,Hsing,645,Germany,Female,59,8,121669.93,2,0,0,91.75,1
5548,5549,15639662,Phillips,710,France,Male,38,2,0.00,2,1,0,96.27,0
4989,4990,15602851,Ozioma,629,France,Male,40,9,0.00,1,1,0,106.67,0

In [127]:
p.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
8926,8927,15709136,Adams,620,France,Male,28,8,0.00,2,1,1,199909.32,0
9096,9097,15762331,Moss,569,France,Male,37,9,178755.84,1,1,0,199929.17,0
4417,4418,15697270,Gannon,608,Spain,Male,27,4,153325.10,1,1,1,199953.33,0
3580,3581,15634359,Dyer,639,Germany,Female,41,5,98635.77,1,1,0,199970.74,0
6646,6647,15662021,Lucciano,685,Spain,Female,42,2,0.00,2,0,0,199992.48,0

In [128]:
import pandas as pd

In [129]:
df = pd.read_csv('/content/covid_toy.csv')

In [130]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [131]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [132]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [133]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [134]:
df['fever'].mean()

np.float64(100.84444444444445)

In [135]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [136]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [137]:
# filter --> filter the records from anywhere where we want
# map -->

In [138]:
df['gender'] = df['gender'].map({'Female':1 , 'Male':0})

In [139]:
df.head(7)

   age  gender       fever   cough       city has_covid
0   60       0  103.000000    Mild    Kolkata        No
1   27       0  100.000000    Mild      Delhi       Yes
2   42       0  101.000000    Mild      Delhi        No
3   31       1   98.000000    Mild    Kolkata        No
4   65       1  101.000000    Mild     Mumbai        No
5   84       1  100.844444    Mild  Bangalore       Yes
6   14       0  101.000000  Strong  Bangalore        No

In [140]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [141]:
df['cough'] = df['cough'].map({'Mild':0, 'Strong' : 1})

In [142]:
df.head()

   age  gender  fever  cough     city has_covid
0   60       0  103.0      0  Kolkata        No
1   27       0  100.0      0    Delhi       Yes
2   42       0  101.0      0    Delhi        No
3   31       1   98.0      0  Kolkata        No
4   65       1  101.0      0   Mumbai        No

In [143]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [144]:
df['has_covid'] = df['has_covid'].map({'Yes':1, 'No':0})

In [145]:
df.head()

   age  gender  fever  cough     city  has_covid
0   60       0  103.0      0  Kolkata          0
1   27       0  100.0      0    Delhi          1
2   42       0  101.0      0    Delhi          0
3   31       1   98.0      0  Kolkata          0
4   65       1  101.0      0   Mumbai          0

In [146]:
df[['fever' , 'has_covid']]

    fever  has_covid
0   103.0          0
1   100.0          1
2   101.0          0
3    98.0          0
4   101.0          0
..    ...        ...
95  104.0          0
96  101.0          1
97  101.0          0
98   98.0          0
99   98.0          1

[100 rows x 2 columns]

In [147]:
df.head(3)

   age  gender  fever  cough     city  has_covid
0   60       0  103.0      0  Kolkata          0
1   27       0  100.0      0    Delhi          1
2   42       0  101.0      0    Delhi          0

In [148]:
df['fever'] = df['fever'].astype(int) # using .astype() we can change datatype

In [149]:
df.head(3)

   age  gender  fever  cough     city  has_covid
0   60       0    103      0  Kolkata          0
1   27       0    100      0    Delhi          1
2   42       0    101      0    Delhi          0

In [150]:
df['age'] = df['age'].astype(float)

In [151]:
df.head(3)

    age  gender  fever  cough     city  has_covid
0  60.0       0    103      0  Kolkata          0
1  27.0       0    100      0    Delhi          1
2  42.0       0    101      0    Delhi          0

In [152]:
df['fever'][1:3] = 50

/tmp/ipykernel_3178/146693501.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['fever'][1:3] = 50
/tmp/ipykernel_3178/146693501.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fever'][1:3] = 50

In [153]:
df.head(3)

    age  gender  fever  cough     city  has_covid
0  60.0       0    103      0  Kolkata          0
1  27.0       0     50      0    Delhi          1
2  42.0       0     50      0    Delhi          0

In [154]:
df['city'][0]='Jaipur'

/tmp/ipykernel_3178/1312264348.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][0]='Jaipur'
/tmp/ipykernel_3178/1312264348.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][0]='Jaipur'

In [155]:
df.head(3)

    age  gender  fever  cough    city  has_covid
0  60.0       0    103      0  Jaipur          0
1  27.0       0     50      0   Delhi          1
2  42.0       0     50      0   Delhi          0

In [156]:
new_data = df.rename(columns = {'cough' : 'updated_cough'})

In [157]:
new_data

     age  gender  fever  updated_cough       city  has_covid
0   60.0       0    103              0     Jaipur          0
1   27.0       0     50              0      Delhi          1
2   42.0       0     50              0      Delhi          0
3   31.0       1     98              0    Kolkata          0
4   65.0       1    101              0     Mumbai          0
..   ...     ...    ...            ...        ...        ...
95  12.0       1    104              0  Bangalore          0
96  51.0       1    101              1    Kolkata          1
97  20.0       1    101              0  Bangalore          0
98   5.0       1     98              1     Mumbai          0
99  10.0       1     98              1    Kolkata          1

[100 rows x 6 columns]

In [158]:
new_data['new_updated_city'] = new_data['city'].where(new_data['city'] == 'Delhi', other = 0)

In [159]:
new_data.head(10)

    age  gender  fever  updated_cough       city  has_covid new_updated_city
0  60.0       0    103              0     Jaipur          0                0
1  27.0       0     50              0      Delhi          1            Delhi
2  42.0       0     50              0      Delhi          0            Delhi
3  31.0       1     98              0    Kolkata          0                0
4  65.0       1    101              0     Mumbai          0                0
5  84.0       1    100              0  Bangalore          1                0
6  14.0       0    101              1  Bangalore          0                0
7  20.0       1    100              1     Mumbai          1                0
8  19.0       1    100              1  Bangalore          0                0
9  64.0       1    101              0      Delhi          0            Delhi

In [160]:
new_data['has_covid'] = new_data['has_covid'].where(new_data['has_covid']==0, other='Positive')

In [161]:
new_data.head(10)

    age  gender  fever  updated_cough       city has_covid new_updated_city
0  60.0       0    103              0     Jaipur         0                0
1  27.0       0     50              0      Delhi  Positive            Delhi
2  42.0       0     50              0      Delhi         0            Delhi
3  31.0       1     98              0    Kolkata         0                0
4  65.0       1    101              0     Mumbai         0                0
5  84.0       1    100              0  Bangalore  Positive                0
6  14.0       0    101              1  Bangalore         0                0
7  20.0       1    100              1     Mumbai  Positive                0
8  19.0       1    100              1  Bangalore         0                0
9  64.0       1    101              0      Delhi         0            Delhi