In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/supply_chain.csv')

In [3]:
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [4]:
df.tail()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
98,skincare,SKU98,19.754605,43,913,8525.952560,Female,53,1,27,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864
99,haircare,SKU99,68.517833,17,627,9185.185829,Unknown,55,8,59,...,Chennai,29,921,2,38.072899,Fail,0.346027,Rail,Route B,210.743009

In [5]:
df.shape

(100, 24)

In [6]:
df.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [7]:
df.dtypes

Product type                object
SKU                         object
Price                      float64
Availability                 int64
Number of products sold      int64
Revenue generated          float64
Customer demographics       object
Stock levels                 int64
Lead times                   int64
Order quantities             int64
Shipping times               int64
Shipping carriers           object
Shipping costs             float64
Supplier name               object
Location                    object
Lead time                    int64
Production volumes           int64
Manufacturing lead time      int64
Manufacturing costs        float64
Inspection results          object
Defect rates               float64
Transportation modes        object
Routes                      object
Costs                      float64
dtype: object

In [8]:
df['Lead times']

0      7
1     30
2     10
3     13
4      3
      ..
95    14
96     2
97    19
98     1
99     8
Name: Lead times, Length: 100, dtype: int64

In [9]:
df['Location']

0      Mumbai
1      Mumbai
2      Mumbai
3     Kolkata
4       Delhi
       ...
95     Mumbai
96     Mumbai
97     Mumbai
98    Chennai
99    Chennai
Name: Location, Length: 100, dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    float64
dtypes: float64(6), int64(9), object(9)
memory usage: 18.9+ KB

In [11]:
categorical_df = df.select_dtypes(include=['category', 'object'])
categorical_df

,Product type,SKU,Customer demographics,Shipping carriers,Supplier name,Location,Inspection results,Transportation modes,Routes
0,haircare,SKU0,Non-binary,Carrier B,Supplier 3,Mumbai,Pending,Road,Route B
1,skincare,SKU1,Female,Carrier A,Supplier 3,Mumbai,Pending,Road,Route B
2,haircare,SKU2,Unknown,Carrier B,Supplier 1,Mumbai,Pending,Air,Route C
3,skincare,SKU3,Non-binary,Carrier C,Supplier 5,Kolkata,Fail,Rail,Route A
4,skincare,SKU4,Non-binary,Carrier A,Supplier 1,Delhi,Fail,Air,Route A
...,...,...,...,...,...,...,...,...,...
95,haircare,SKU95,Unknown,Carrier B,Supplier 4,Mumbai,Pending,Air,Route A
96,cosmetics,SKU96,Non-binary,Carrier C,Supplier 3,Mumbai,Pending,Road,Route A
97,haircare,SKU97,Male,Carrier A,Supplier 4,Mumbai,Fail,Road,Route A
98,skincare,SKU98,Female,Carrier B,Supplier 5,Chennai,Pending,Rail,Route A
99,haircare,SKU99,Unknown,Carrier B,Supplier 2,Chennai,Fail,Rail,Route B

In [12]:
integer_df = df.select_dtypes(include = ['category', 'int'])
integer_df

,Availability,Number of products sold,Stock levels,Lead times,Order quantities,Shipping times,Lead time,Production volumes,Manufacturing lead time
0,55,802,58,7,96,4,29,215,29
1,95,736,53,30,37,2,23,517,30
2,34,8,1,10,88,2,12,971,27
3,68,83,23,13,59,6,24,937,18
4,26,871,5,3,56,8,5,414,3
...,...,...,...,...,...,...,...,...,...
95,65,672,15,14,26,9,18,450,26
96,29,324,67,2,32,3,28,648,28
97,56,62,46,19,4,9,10,535,13
98,43,913,53,1,27,7,28,581,9
99,17,627,55,8,59,6,29,921,2

In [13]:
float_df = df.select_dtypes(include = ['category', 'float'])
float_df

,Price,Revenue generated,Shipping costs,Manufacturing costs,Defect rates,Costs
0,69.808006,8661.996792,2.956572,46.279879,0.226410,187.752075
1,14.843523,7460.900065,9.716575,33.616769,4.854068,503.065579
2,11.319683,9577.749626,8.054479,30.688019,4.580593,141.920282
3,61.163343,7766.836426,1.729569,35.624741,4.746649,254.776159
4,4.805496,2686.505152,3.890548,92.065161,3.145580,923.440632
...,...,...,...,...,...,...
95,77.903927,7386.363944,8.630339,58.890686,1.210882,778.864241
96,24.423131,7698.424766,5.352878,17.803756,3.872048,188.742141
97,3.526111,4370.916580,7.904846,65.765156,3.376238,540.132423
98,19.754605,8525.952560,1.409801,5.604691,2.908122,882.198864
99,68.517833,9185.185829,1.311024,38.072899,0.346027,210.743009

In [14]:
df.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [15]:
integer_df.value_counts()

Availability  Number of products sold  Stock levels  Lead times  Order quantities  Shipping times  Lead time  Production volumes  Manufacturing lead time
1             24                       93            7           52                6               25         794                 25                         1
              820                      64            11          11                1               10         727                 27                         1
3             253                      45            5           67                7               16         329                 7                          1
5             249                      80            8           48                9               23         173                 10                         1
              963                      25            8           21                9               24         867                 15                         1
                                                                                                                                                            ..
97            933                      90            20          39                8               18         793                 1                          1
              987                      77            26          72                9               12         908                 14                         1
98            155                      22            27          57                4               26         179                 7                          1
99            618                      73            26          80                10              24         589                 22                         1
100           187                      48            11          94                3               20         694                 16                         1
Name: count, Length: 100, dtype: int64

In [16]:
categorical_df.value_counts()

Product type  SKU    Customer demographics  Shipping carriers  Supplier name  Location   Inspection results  Transportation modes  Routes
cosmetics     SKU17  Female                 Carrier C          Supplier 1     Chennai    Fail                Air                   Route C    1
              SKU21  Unknown                Carrier B          Supplier 5     Chennai    Pending             Air                   Route C    1
              SKU23  Unknown                Carrier A          Supplier 5     Kolkata    Pending             Rail                  Route A    1
              SKU27  Unknown                Carrier C          Supplier 5     Mumbai     Fail                Sea                   Route B    1
              SKU28  Female                 Carrier B          Supplier 1     Mumbai     Fail                Air                   Route A    1
                                                                                                                                             ..
skincare      SKU82  Unknown                Carrier A          Supplier 2     Mumbai     Pending             Road                  Route C    1
              SKU86  Unknown                Carrier B          Supplier 1     Mumbai     Pass                Rail                  Route A    1
              SKU9   Unknown                Carrier A          Supplier 2     Chennai    Pending             Rail                  Route B    1
              SKU90  Non-binary             Carrier B          Supplier 3     Bangalore  Pass                Rail                  Route B    1
              SKU98  Female                 Carrier B          Supplier 5     Chennai    Pending             Rail                  Route A    1
Name: count, Length: 100, dtype: int64

In [17]:
categorical_df['Customer demographics'].value_counts()

Customer demographics
Unknown       31
Female        25
Non-binary    23
Male          21
Name: count, dtype: int64

In [18]:
categorical_df['Shipping carriers'].value_counts()

Shipping carriers
Carrier B    43
Carrier C    29
Carrier A    28
Name: count, dtype: int64

In [19]:
categorical_df['Location'].value_counts()

Location
Kolkata      25
Mumbai       22
Chennai      20
Bangalore    18
Delhi        15
Name: count, dtype: int64

In [20]:
categorical_df['Inspection results'].value_counts()

Inspection results
Pending    41
Fail       36
Pass       23
Name: count, dtype: int64

In [21]:
categorical_df['Transportation modes'].value_counts()

Transportation modes
Road    29
Rail    28
Air     26
Sea     17
Name: count, dtype: int64

In [22]:
categorical_df['Routes'].value_counts()

Routes
Route A    43
Route B    37
Route C    20
Name: count, dtype: int64

In [23]:
float_df.describe()

,Price,Revenue generated,Shipping costs,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,49.462461,5776.048187,5.548149,47.266693,2.277158,529.245782
std,31.168193,2732.841744,2.651376,28.982841,1.461366,258.301696
min,1.699976,1061.618523,1.013487,1.085069,0.018608,103.916248
25%,19.597823,2812.847151,3.540248,22.983299,1.009650,318.778455
50%,51.239831,6006.352023,5.320534,45.905622,2.141863,520.430444
75%,77.198228,8253.976921,7.601695,68.621026,3.563995,763.078231
max,99.171329,9866.465458,9.929816,99.466109,4.939255,997.413450

In [24]:
integer_df.describe()

,Availability,Number of products sold,Stock levels,Lead times,Order quantities,Shipping times,Lead time,Production volumes,Manufacturing lead time
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000
mean,48.400000,460.990000,47.770000,15.960000,49.220000,5.750000,17.080000,567.840000,14.77000
std,30.743317,303.780074,31.369372,8.785801,26.784429,2.724283,8.846251,263.046861,8.91243
min,1.000000,8.000000,0.000000,1.000000,1.000000,1.000000,1.000000,104.000000,1.00000
25%,22.750000,184.250000,16.750000,8.000000,26.000000,3.750000,10.000000,352.000000,7.00000
50%,43.500000,392.500000,47.500000,17.000000,52.000000,6.000000,18.000000,568.500000,14.00000
75%,75.000000,704.250000,73.000000,24.000000,71.250000,8.000000,25.000000,797.000000,23.00000
max,100.000000,996.000000,100.000000,30.000000,96.000000,10.000000,30.000000,985.000000,30.00000

In [25]:
integer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Availability             100 non-null    int64
 1   Number of products sold  100 non-null    int64
 2   Stock levels             100 non-null    int64
 3   Lead times               100 non-null    int64
 4   Order quantities         100 non-null    int64
 5   Shipping times           100 non-null    int64
 6   Lead time                100 non-null    int64
 7   Production volumes       100 non-null    int64
 8   Manufacturing lead time  100 non-null    int64
dtypes: int64(9)
memory usage: 7.2 KB

In [26]:
float_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Price                100 non-null    float64
 1   Revenue generated    100 non-null    float64
 2   Shipping costs       100 non-null    float64
 3   Manufacturing costs  100 non-null    float64
 4   Defect rates         100 non-null    float64
 5   Costs                100 non-null    float64
dtypes: float64(6)
memory usage: 4.8 KB

In [27]:
df.size

2400

In [28]:
df.empty

False

In [29]:
df = df.dropna()

In [30]:
df.ndim

2

In [31]:
df.values

array([['haircare', 'SKU0', 69.80800554211577, ..., 'Road', 'Route B',
        187.75207545920392],
       ['skincare', 'SKU1', 14.84352327508434, ..., 'Road', 'Route B',
        503.0655791496692],
       ['haircare', 'SKU2', 11.319683293090566, ..., 'Air', 'Route C',
        141.92028177151906],
       ...,
       ['haircare', 'SKU97', 3.526111259143416, ..., 'Road', 'Route A',
        540.1324228679678],
       ['skincare', 'SKU98', 19.7546048668786, ..., 'Rail', 'Route A',
        882.1988635470415],
       ['haircare', 'SKU99', 68.51783269927664, ..., 'Rail', 'Route B',
        210.74300896424612]], dtype=object)